version: '3'
services:
  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: amm_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_HOST: postgres
      PORT: 5432
    ports:
      - "15010:15010"
    networks:
      - amm_net
    restart: on-failure

networks:
  amm_net:
    driver: bridge