version: '3'
services:
  producer2:
    build:
      context: .
      dockerfile: producer/Dockerfile
    networks:
      - amm_net
    command: ["python", "producer/producer.py", "--service-name", "producer2"]
    restart: on-failure

networks:
  amm_net:
    driver: bridge
